"""add optimization_tip table

Revision ID: 72f0fa9dfbeb
Revises: dd472cc97474
Create Date: 2025-04-15 21:56:51.517837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72f0fa9dfbeb'
down_revision = 'dd472cc97474'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('optimization_tip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('social_page_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('implementation_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['social_page_id'], ['social_page.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('optimization_tip', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_optimization_tip_social_page_id'), ['social_page_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('optimization_tip', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_optimization_tip_social_page_id'))

    op.drop_table('optimization_tip')
    # ### end Alembic commands ###
