"""Add social media ID columns to User model

Revision ID: 828233b29ccb
Revises: 
Create Date: 2025-04-13 00:16:57.442750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '828233b29ccb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('facebook_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('instagram_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('tiktok_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('profile_image', sa.String(length=500), nullable=True))
        batch_op.create_unique_constraint(None, ['tiktok_id'])
        batch_op.create_unique_constraint(None, ['facebook_id'])
        batch_op.create_unique_constraint(None, ['instagram_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('profile_image')
        batch_op.drop_column('tiktok_id')
        batch_op.drop_column('instagram_id')
        batch_op.drop_column('facebook_id')

    # ### end Alembic commands ###
